CREATE TABLE reviews (
                         review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         reviewer_id NUMBER,
                         movie_id NUMBER,
                         review_rating NUMBER(2,1),
                         review_content VARCHAR2(1000),
                         review_created_at DATE,
                         FOREIGN KEY (reviewer_id) REFERENCES members(member_id),
                         FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
);