CREATE TABLE reviews (
                         review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         member_id NUMBER,
                         movie_id NUMBER,
                         review_rating NUMBER(2,1) NOT NULL,
                         review_content VARCHAR2(1000) NOT NULL,
                         review_created_at DATE,
                         FOREIGN KEY (member_id) REFERENCES members(member_id),
                         FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
);