CREATE TABLE members (
                         member_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         member_name VARCHAR2(100),
                         kakao_platform_id VARCHAR2(100),
                         member_profile_img VARCHAR2(255)
);