CREATE TABLE reviews (
                         review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         reviewer_id NUMBER NOT NULL,
                         movie_id NUMBER NOT NULL,
                         review_rating NUMBER(2,1) NOT NULL,
                         review_content VARCHAR2(1000) NOT NULL,
                         review_created_at DATE NOT NULL,
                         FOREIGN KEY (reviewer_id) REFERENCES members(member_id) ON DELETE CASCADE,
                         FOREIGN KEY (movie_id) REFERENCES movies(movie_id) ON DELETE CASCADE
);